# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('status', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('activity_description', models.CharField(max_length=4000)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audit.Type')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_projeto', to='register.Client')),
                ('ey_employee_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_employee')),
            ],
        ),
        migrations.CreateModel(
            name='Service_style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='service_style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Service_style'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='status.List'),
        ),
    ]
