# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20161103_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_client',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Activity'),
        ),
        migrations.AlterField(
            model_name='activity_client',
            name='client_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client_employee'),
        ),
        migrations.AlterField(
            model_name='activity_ey',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Activity'),
        ),
        migrations.AlterField(
            model_name='activity_ey',
            name='ey_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_employee'),
        ),
    ]
