# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20161031_1027'),
        ('project', '0003_auto_20161103_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_EY_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blabla', models.CharField(max_length=250)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Activity')),
                ('ey_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_employee')),
            ],
        ),
    ]
