# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_activity_ey_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_ey_new',
            old_name='activity',
            new_name='activity_tiu',
        ),
        migrations.RenameField(
            model_name='activity_ey_new',
            old_name='ey_employee',
            new_name='ey_employee_tiu',
        ),
    ]
