# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20161103_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity_ey_new',
            name='activity_tiu',
        ),
        migrations.RemoveField(
            model_name='activity_ey_new',
            name='ey_employee_tiu',
        ),
        migrations.DeleteModel(
            name='Activity_EY_new',
        ),
    ]
