# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_name', models.CharField(max_length=100)),
                ('received_description', models.CharField(max_length=250)),
                ('received_format', models.CharField(max_length=25)),
                ('received_version', models.CharField(max_length=10)),
                ('received_path', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=250)),
                ('template_description', models.CharField(max_length=250)),
                ('template_format', models.CharField(max_length=25)),
                ('template_version', models.CharField(max_length=10)),
                ('template_path', models.CharField(max_length=500)),
                ('audit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audit.Type')),
                ('template_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_employee')),
            ],
        ),
    ]
