# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20161031_1027'),
        ('documents', '0002_auto_20161031_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Client_employee')),
                ('ey_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Ey_employee')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Template')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='resend_reason',
            field=models.CharField(default='', max_length=500),
        ),
    ]
