# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20161103_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='resend_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='send_counter',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
