# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20161018_1551'),
        ('project', '0001_initial'),
        ('documents', '0003_auto_20161018_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Activity'),
        ),
        migrations.AddField(
            model_name='request',
            name='client_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client_employee'),
        ),
        migrations.AddField(
            model_name='request',
            name='ey_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_employee'),
        ),
        migrations.AddField(
            model_name='request',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Template'),
        ),
        migrations.AddField(
            model_name='received',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.Activity'),
        ),
        migrations.AddField(
            model_name='received',
            name='client_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client_employee'),
        ),
        migrations.AddField(
            model_name='received',
            name='ey_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_employee'),
        ),
        migrations.AddField(
            model_name='received',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Template'),
        ),
    ]
