# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20161103_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_path',
            field=models.CharField(default='xxx', max_length=500),
            preserve_default=False,
        ),
    ]
