# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20161018_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='client_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client_employee'),
        ),
        migrations.AlterField(
            model_name='received',
            name='ey_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_employee'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client_employee'),
        ),
        migrations.AlterField(
            model_name='request',
            name='ey_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_employee'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_employee'),
        ),
    ]
