# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Client_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_employee_name', models.CharField(max_length=250)),
                ('client_employee_email', models.CharField(max_length=100)),
                ('client_employee_telephone', models.CharField(max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Client_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_position_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Client_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ey_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ey_employee_name', models.CharField(max_length=250)),
                ('ey_employee_email', models.CharField(max_length=100)),
                ('ey_employee_telephone', models.CharField(max_length=25)),
                ('ey_employee_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ey_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ey_position_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='ey_employee',
            name='ey_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Ey_position'),
        ),
        migrations.AddField(
            model_name='client_employee',
            name='client_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client_position'),
        ),
        migrations.AddField(
            model_name='client_employee',
            name='client_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Client_type'),
        ),
    ]
