# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='client_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_employee_name', models.CharField(max_length=250)),
                ('client_employee_email', models.CharField(max_length=100)),
                ('client_employee_telephone', models.CharField(max_length=25)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.client')),
            ],
        ),
        migrations.CreateModel(
            name='client_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_position_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='client_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='client_employee',
            name='client_position_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.client_position'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.client_type'),
        ),
    ]
