# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_type_id',
            new_name='client_type',
        ),
        migrations.RenameField(
            model_name='client_employee',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='client_employee',
            old_name='client_position_id',
            new_name='client_position',
        ),
    ]
