# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_employee',
            old_name='client_user_id',
            new_name='client_user',
        ),
        migrations.RenameField(
            model_name='ey_employee',
            old_name='ey_employee_user_id',
            new_name='ey_employee_user',
        ),
    ]
