# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20161018_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ey_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ey_employee_name', models.CharField(max_length=250)),
                ('ey_employee_email', models.CharField(max_length=100)),
                ('ey_employee_telephone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ey_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ey_position_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='ey_employee',
            name='ey_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.ey_position'),
        ),
    ]
