# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_reference', models.CharField(max_length=10)),
                ('list_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_current_status', models.CharField(max_length=10)),
                ('workflow_success_next_status', models.CharField(max_length=10)),
                ('workflow_fail_next_status', models.CharField(max_length=10)),
            ],
        ),
    ]
