# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workflow',
            old_name='workflow_next_status',
            new_name='workflow_fail_next_status',
        ),
        migrations.AddField(
            model_name='workflow',
            name='workflow_success_next_status',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
