# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_auto_20161031_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_name', models.CharField(max_length=250)),
                ('definition_description', models.CharField(max_length=250)),
                ('definition_column', models.CharField(max_length=100)),
                ('definition_line', models.CharField(max_length=100)),
                ('definition_rule', models.CharField(max_length=100)),
                ('definition_result', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='definitions',
            name='definition_operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.Operator'),
        ),
        migrations.AddField(
            model_name='definitions',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Template'),
        ),
    ]
