# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20161018_1551'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_name', models.CharField(max_length=250)),
                ('definition_description', models.CharField(max_length=250)),
                ('definition_column', models.CharField(max_length=100)),
                ('definition_line', models.CharField(max_length=100)),
                ('definition_rule', models.CharField(max_length=100)),
                ('definition_result', models.CharField(max_length=2000)),
                ('definition_operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rules.Operator')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.Template')),
            ],
        ),
    ]
